version: "3"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
     # - PASSWORD=password     ## Uncomment to enable basic authentication, username = podgrab
    volumes:
      - ./.config/podgrab_config:/config
      - ./media/Podcasts/:/assets
    ports:
      - 1114:8080
    restart: unless-stopped
  navidrome_music:
    image: deluan/navidrome:latest
    user: 0:0 # should be owner of volumes
      # Outside:Inside container
    ports:
      - "1111:4533"
    restart: unless-stopped
    volumes:
      - "./.config/navidrome_data/music_instance:/data"
      - "./media/Music/:/music:ro"
  navidrome_podcasts:
    image: deluan/navidrome:latest
    user: 0:0 # should be owner of volumes
    ports:
      - "1112:4533"
    restart: unless-stopped
    volumes:
      - "./.config/navidrome_data/podcast_instance:/data"
      - "./media/Podcasts/:/music:ro"
